<meta charset="utf-8">
<style>
	body { 
		margin-top: 10; 
		background-color: rgb(255, 255, 255);
	}
	p {
		font-size: 10;
		font-family: Verdana;
		color: #000000;
	}
	table {
		align-content: center;
		font-family: Verdana;
		margin: auto;
	}
	th, tr {  
		width: 200;
	}
	img { width: 100; height: 100; }
	.block1{
		width: 900;
		height: 200;
		background-color: rgb(230, 230, 230)
	}
	.s1_block1 {
		width: 200;
		height: 200;
		float: left;
	}
	.s2_block1 {
		width: 600;
		height: 200;
		float: right;
	}
	.block2{
		width: 900;
	}
</style>